### DISCUSSION TITLE
The heap is constantly increasing

### DISCUSSION THREAD

**Discussion by huifer** [rabbitmq/amqp091-go#268] [Q&A]
**Describe the bug**
The heap is constantly increasing

my code 
```

	preHandlerMessage, err := ch.Consume("pre_handler", // queue
		"",    // consumer
		true,  // auto-ack
		false, // exclusive
		false, // no-local
		true,  // no-wait
		nil,   // args
	)


func HandlerDataStorage(messages <-chan amqp.Delivery, ch *amqp.Channel) {

	go func() {

		for d := range messages {
			// todo: storage
			

		}
	}()

	zap.S().Infof(" [*] Waiting for messages. To exit press CTRL+C")
}

```

<img width="888" alt="image" src="https://github.com/rabbitmq/amqp091-go/assets/26766909/30e440bb-f87a-4024-a66c-bb9f3fc106ca">

**Comment by lukebakken** [comment]
Hello, thanks for using this library.

Please, help us help you and make it easy for us to reproduce your issue. That means -
* Provide code we can clone and run to see the issue. In your case, this means a simple application to publish messages (or PerfTest) and a consuming application that demonstrates this issue. Please make this code _runnable_.
* What version of RabbitMQ and Erlang are you using?
* What version of Go?
* How are you collecting that memory information? It is unfamiliar to me.

Thank you.

**Reply by huifer** [reply]
main code 
```
	CreateRabbitQueue("a")
	ch, err := GRabbitMq.Channel()
	failOnError(err, "Failed to open a channel")

	preHandlerMessage, err := ch.Consume("a", // queue
		"",    // consumer
		true,  // auto-ack
		false, // exclusive
		false, // no-local
		true,  // no-wait
		nil,   // args
	)
go func() {
		for d := range preHandlerMessage {
			zap.S().Infof("%s",string(d.Body))
		}
	}()

```

push message 
```
for true {
		err = ch.PublishWithContext(context.Background(), "", "a", // routing key
			false, // mandatory
			false, // immediate
			amqp.Publishing{
				ContentType: "text/plain",
				Body:        jsonData,
			})
		failOnError(err, "Failed to publish a message")
		log.Printf(" [x] Sent %s\n", jsonData)
		time.Sleep(1 * time.Second)
	}
```

- rabbitmq version

```
version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./log/:/var/log/rabbitmq
      - ./plugins:/usr/lib/rabbitmq/plugins
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
    environment:
      - RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
```
- Collection method
```
	_ "net/http/pprof"

```

- go version
```
go version go1.22.3 darwin/amd64
```
